on:
  push:
     branches:
       - main
  schedule:
    - cron:  '0 1 * * *'

name: i-like-the-stock-render

jobs:
  bookdown:
    name: renderbook
    #runs-on: macOS-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      #- uses: r-lib/actions/setup-r@v1
      - name: Renviron
        run: echo FRED_API=${{ secrets.FRED_API }} >> Renviron.site
      - name: Render Book from Action
        uses: ckrusemd/rmarkdown-action@v0.18
        with:
           input_file: index.Rmd
      - uses: actions/upload-artifact@v1
        with:
          name: _book
          path: _book/

  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: bookdown
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
        name: _book # optional
        path: _book # optional
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      with:
        build_dir: _book/
        email: ${{ secrets.EMAIL }}  #optional
        jekyll: no                     # optional
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EMAIL: ${{ secrets.EMAIL }}
        BUILD_DIR: _book/
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: ${{secrets.MAIL_USERNAME}}
        password: ${{secrets.MAIL_PASSWORD}}
        subject: Danish Electricity Prices - Daily Update
        to: ${{secrets.MAIL_USERNAME}}
        from: Christian Kruse
        secure: true
        body: https://ckrusemd.github.io/danish-electricity-prices/east-denmark.html
